In [35]:
# importing libraries 
import pandas as pd 
import matplotlib.pyplot as plt
from datasets import load_dataset

# loading dataset 
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# data cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [36]:
df_salary = df[pd.notna(df['salary_year_avg'])].copy()

In [37]:
def calculate_salary(salary):
    return salary * 1.03

In [38]:
df_salary['inflated_salary'] = df['salary_year_avg'].apply(calculate_salary)

In [39]:
df_salary[['salary_year_avg','inflated_salary']]

        salary_year_avg  inflated_salary
28             109500.0        112785.00
77             140000.0        144200.00
92             120000.0        123600.00
100            228222.0        235068.66
109             89000.0         91670.00
...                 ...              ...
785624         139216.0        143392.48
785641         150000.0        154500.00
785648         221875.0        228531.25
785682         157500.0        162225.00
785692         157500.0        162225.00

[22003 rows x 2 columns]

In [40]:
df_salary['inflated_salary2'] = df_salary['salary_year_avg'].apply(lambda salary: salary * 1.03)

In [41]:
df_salary[['salary_year_avg','inflated_salary','inflated_salary2']]

        salary_year_avg  inflated_salary  inflated_salary2
28             109500.0        112785.00         112785.00
77             140000.0        144200.00         144200.00
92             120000.0        123600.00         123600.00
100            228222.0        235068.66         235068.66
109             89000.0         91670.00          91670.00
...                 ...              ...               ...
785624         139216.0        143392.48         143392.48
785641         150000.0        154500.00         154500.00
785648         221875.0        228531.25         228531.25
785682         157500.0        162225.00         162225.00
785692         157500.0        162225.00         162225.00

[22003 rows x 3 columns]

In [42]:
df.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."

In [43]:
print(df['job_skills'][1])
type(df['job_skills'][1])

['r', 'python', 'sql', 'nosql', 'power bi', 'tableau']

str

In [44]:
import ast   # module of python standard library 

def skills_list(job_skills):
    if pd.notna(job_skills):
        return ast.literal_eval(job_skills)     # literal eval function converts string of list into list

In [45]:

# df['job_skills']  = df['job_skills'].apply(skills_list)

In [46]:
type(df['job_skills'][1])

str

With lambda

In [47]:
df['job_skills_l'] = df['job_skills'].apply(lambda job_skills: ast.literal_eval(job_skills) if pd.notna(job_skills) else job_skills)

In [53]:
print(df['job_skills_l'][1])
type(df['job_skills_l'][1])

['r', 'python', 'sql', 'nosql', 'power bi', 'tableau']

list

## Apply function with rows

Senior 1.05  
Rest 1.03

In [49]:
def project_salary(row):
    if 'Senior' in row['job_title_short']:
        return 1.05 * row['salary_year_avg']
    else :
        return 1.03 * row['salary_year_avg']

In [50]:
df_salary['inflated_salary'] = df_salary.apply(project_salary,axis = 1)

In [51]:
df_salary[['job_title_short','salary_year_avg','inflated_salary']]

       job_title_short  salary_year_avg  inflated_salary
28      Data Scientist         109500.0        112785.00
77       Data Engineer         140000.0        144200.00
92       Data Engineer         120000.0        123600.00
100     Data Scientist         228222.0        235068.66
109       Data Analyst          89000.0         91670.00
...                ...              ...              ...
785624   Data Engineer         139216.0        143392.48
785641   Data Engineer         150000.0        154500.00
785648  Data Scientist         221875.0        228531.25
785682  Data Scientist         157500.0        162225.00
785692  Data Scientist         157500.0        162225.00

[22003 rows x 3 columns]

In [61]:
df_salary['inflated_salary_lambda'] = df_salary.apply(lambda row: 1.05 * row['salary_year_avg'] if 'Senior' in row['job_title_short'] else row['salary_year_avg'] * 1.03, axis = 1)

In [64]:
df_salary[['job_title_short','salary_year_avg','inflated_salary','inflated_salary_lambda']].head(20)

,job_title_short,salary_year_avg,inflated_salary,inflated_salary_lambda
28,Data Scientist,109500.0,112785.00,112785.00
77,Data Engineer,140000.0,144200.00,144200.00
92,Data Engineer,120000.0,123600.00,123600.00
100,Data Scientist,228222.0,235068.66,235068.66
109,Data Analyst,89000.0,91670.00,91670.00
116,Data Scientist,114000.0,117420.00,117420.00
146,Data Engineer,129500.0,133385.00,133385.00
180,Data Analyst,90250.0,92957.50,92957.50
212,Data Scientist,157500.0,162225.00,162225.00
257,Data Scientist,103128.0,106221.84,106221.84
307,Data Engineer,185000.0,190550.00,190550.00
339,Data Engineer,195000.0,200850.00,200850.00
380,Data Engineer,97500.0,100425.00,100425.00
388,Data Engineer,89000.0,91670.00,91670.00
410,Data Analyst,133285.0,137283.55,137283.55
450,Data Scientist,157500.0,162225.00,162225.00
495,Senior Data Engineer,168500.0,176925.00,176925.00
520,Business Analyst,63000.0,64890.00,64890.00
545,Data Engineer,80000.0,82400.00,82400.00
571,Data Engineer,110000.0,113300.00,113300.00